config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
      resources :admin_users
      resources :employees
      resources :users
      resources :posts
      root to: "users#index"
  end
  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#homepage'
end

app/views/shared/_admin_drowpdown.html.erb
<% if current_user.try(:type) =='AdminUser' %>
  <li>
    <%= link_to "Admin Dashboard", admin_root_path %>
  </li>
<% end %>

app/views/shared/_audit_log_tab.html.erb
<li class="nav-item">
  <%= link_to "Audit Log", audit_logs_path, class: "nav-link #{active?(posts_path)} " %>
</li>

app/views/shared/_employee_nav_items.html.erb
<li class="nav-item">
    <%= link_to "Entries", posts_path, class: "nav-link #{active?(posts_path)}" %>
</li>

<li class="nav-item">
    <%= link_to "Request Overtime Approval", new_post_path, class: "nav-link #{active?(new_post_path)}", id: "new_post_from_nav" %>
</li>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |msg| %>
    <%= js add_gritter(msg, :image => :error, :title => "Overtime Application", :sticky => false) %>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<div class="logo">
  <h1>Time Tracker</h1>
</div>

<ul class="nav nav-tabs custom-nav">
  <li class="nav-item">
    <%= link_to "", root_path, class: "nav-link #{active?(root_path)} glyphicon glyphicon-home" %>
  </li>
  <% if current_user %>
    <%= render 'shared/employee_nav_items' if employee? %>
    <%= render 'shared/audit_log_tab' if admin? %>

  <% end %>
  <li class="dropdown float-right <%#= active?(edit_user_registration_path)%> ">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
    <ul class="dropdown-menu">

      <%= render 'shared/admin_drowpdown' if admin? %>

      <li role="separator" class="divider"></li>
      <% if current_user %>
        <li><%= link_to "Log out",  destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log In",  new_user_session_path %></li>
      <% end %>

    </ul>
  </li>
</ul>